## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.DataFrame(np.random.standard_normal((1000,4)))
data

0         1         2         3
0   -0.443526 -0.596920  1.112851 -0.356551
1    1.871245 -0.232812  0.427770  0.612642
2    1.152777 -2.245290  1.452540 -1.155237
3    0.120400 -0.984006  1.064685 -0.114440
4   -0.177775 -0.772712  1.110102 -1.001511
..        ...       ...       ...       ...
995 -0.377194  0.407422  1.228147 -0.584976
996 -0.764660  0.619188 -0.092423 -3.310515
997 -1.509414 -0.788265  1.743283  1.225228
998 -0.272295  0.395912 -1.127183  0.238946
999 -0.018689  0.830689 -0.491347  0.711279

[1000 rows x 4 columns]

In [3]:
col=data[2]
col

0      1.112851
1      0.427770
2      1.452540
3      1.064685
4      1.110102
         ...   
995    1.228147
996   -0.092423
997    1.743283
998   -1.127183
999   -0.491347
Name: 2, Length: 1000, dtype: float64

In [4]:
col[col.abs()>3]

35     3.256997
532   -3.061979
Name: 2, dtype: float64

In [5]:
data[(data.abs()>3).any(axis='columns')]

0         1         2         3
26  -0.328384  3.156089 -0.779151 -0.136094
35  -1.401090  0.374195  3.256997 -1.254408
153  0.220138  3.821666  0.710369  0.929363
201 -0.474325  3.264410  0.807246 -0.815455
429  0.374743 -3.323061  1.174103  1.661779
532  1.085319  0.856261 -3.061979 -2.127970
669  0.703712  3.235725  1.516899  0.703622
686 -3.428585  0.729821  0.893122 -0.198363
727 -3.500910  1.537072 -0.718423  1.732991
950  1.008675  3.138986  1.527867 -0.106335
996 -0.764660  0.619188 -0.092423 -3.310515

In [6]:
data[(data.abs()>3).any(axis='columns')]=np.sign(data)*2
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.075328     0.044955    -0.043735    -0.031453
std       1.019782     1.019592     0.994824     1.013973
min      -2.848668    -2.984400    -2.991150    -2.843822
25%      -0.811977    -0.644505    -0.701246    -0.729068
50%      -0.055791     0.028778    -0.050182    -0.015952
75%       0.630656     0.754262     0.616710     0.700256
max       2.712247     2.737256     2.453780     2.639154

In [7]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1  1.0 -1.0  1.0  1.0
2  1.0 -1.0  1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0 -1.0  1.0 -1.0

# Permuations and random sampling

In [8]:
permu=pd.DataFrame(np.arange(5*7).reshape((5,7)))
permu

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [9]:
sampler=np.random.permutation(3)
sampler

array([1, 2, 0])

In [10]:
permu.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [11]:
permu.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [12]:
column_sampler=np.random.permutation(7)
column_sampler

array([5, 0, 6, 4, 3, 2, 1])

In [13]:
permu.take(column_sampler,axis='columns')

5   0   6   4   3   2   1
0   5   0   6   4   3   2   1
1  12   7  13  11  10   9   8
2  19  14  20  18  17  16  15
3  26  21  27  25  24  23  22
4  33  28  34  32  31  30  29

In [14]:
permu.sample(2)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [15]:
choices=pd.Series([5,7,-1,6,4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [16]:
choices.sample(n=6,replace=True)

0    5
4    4
0    5
4    4
0    5
3    6
dtype: int64

In [17]:
data=pd.DataFrame({'key':['b','b','a','c','a','b'],
                   'values':range(6)
                   })
data

key  values
0   b       0
1   b       1
2   a       2
3   c       3
4   a       4
5   b       5

In [18]:
pd.get_dummies(data['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [19]:
dummies=pd.get_dummies(data['key'],prefix='col')
df_with_dummy=data[['values']].join(dummies)
df_with_dummy

values  col_a  col_b  col_c
0       0      0      1      0
1       1      0      1      0
2       2      1      0      0
3       3      0      0      1
4       4      1      0      0
5       5      0      1      0

In [20]:
np.random.seed(12345) # to make repeatable
values=np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [21]:
bin=[0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values,bin))


(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [22]:
# extension data types
s=pd.Series([1,2,3,None])
s


0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [23]:
s.dtype

dtype('float64')

In [24]:
# now we gonna set int64
s=pd.Series([1,2,3,None],dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [25]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

s.dtype # INT64Dtype()

In [26]:
s[3] is pd.NA # True

True

In [27]:
a=pd.Series([1,2,3,None],dtype='Int64')
a

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [28]:
a.dtype

Int64Dtype()

In [29]:
b=pd.Series(['one','two',None,'three'],dtype=pd.StringDtype())
# b.dtype # string
b

0      one
1      two
2     <NA>
3    three
dtype: string

In [30]:
df=pd.DataFrame({'A':[1,2,None,3],
                        'B':['one','two','three',None],
                        'C':[False,None,False,True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  3.0   None   True

In [31]:
# String manipualtion
value="a, b, guido"
value.split(',')


['a', ' b', ' guido']

In [32]:
pieces=[x.strip() for x in value.split(',')]
pieces

['a', 'b', 'guido']

In [33]:
first,second,third=pieces
first+"::"+second+"::"+third

'a::b::guido'

In [34]:
"::".join(pieces)

'a::b::guido'

In [35]:
value.find(',,')

-1

In [36]:
# Regular Expressions
import re

text="foo bar\t baz \tqux"
re.split(r"\s+",text)

['foo', 'bar', 'baz', 'qux']

In [37]:
regex=re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [38]:
regex.findall(text)

[' ', '\t ', ' \t']

In [39]:
text="""Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@gmail.com"""
pattern=r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes regex case insensitive
regex=re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@gmail.com']

In [40]:
m=regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [41]:
text[m.start():m.end()]

'dave@google.com'

In [42]:
print(regex.match(text))

None


In [43]:
pattern=r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex=re.compile(pattern,flags=re.IGNORECASE)

m=regex.match('njaganmpm@gmail.com')
m.groups()

('njaganmpm', 'gmail', 'com')

In [44]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'gmail', 'com')]

In [45]:
# string functions with pandas
data=pd.Series({'Dave':'dave@google.com','Steve':'steve@gmail.com',
                'Rob':'rob@gmail.com','Wes':np.nan})

data


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [46]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [47]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [48]:
data_as_string=data.astype('string')
data_as_string

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [49]:
data_as_string.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [50]:
pattern=r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [51]:
matches=data.str.findall(pattern,flags=re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [52]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [53]:
matches.str[:]

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [54]:
data.str.extract(pattern,flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [55]:
# Categorical Data
values=pd.Series(['apple','orange','apple','apple']*2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [56]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [57]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [58]:
values=pd.Series([0,1,0]*2)
dim=pd.Series(['apple','orange'])

In [59]:
values

0    0
1    1
2    0
3    0
4    1
5    0
dtype: int64

In [60]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
1    orange
0     apple
dtype: object

In [61]:
# string manipulation
data={"Dave":"dave@google.com","Steve":"steve@gmail.com","Rob":"rob@gmail.com","Wes":np.nan}
data=pd.Series(data)

In [62]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [63]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [64]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [65]:
data_as_text=data.astype('string')
data_as_text

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [66]:
data_as_text.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [67]:
# Categorical data
values=pd.Series(['apple','orange','apple','apple']*2)

In [68]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

usually pandas have special attribute for to find unique values

In [69]:
pd.unique(values)
pd.value_counts(values)

apple     6
orange    2
dtype: int64

categorical representation significantly improve performance when you using analystics.

In [70]:
values=pd.Series([0,1,0,0]*2)
dim=pd.Series(['apple','orange'])
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [ ]:
# Categorical extension type in pandas
fruits=['apple','orange','apple','apple']*2
N=len(fruits)
rng=np.random.default_rng(seed=12345)
data=pd.DataFrame({'fruits':fruits,
                   'basket_id':np.arange(N),
                   'count':rng.integers(3,15,size=N),
                   'weight':rng.uniform(0,4,size=N)
                   },columns=['fruits','basket_id','count','weight'])
data

In [80]:
fruits_cat=data['fruits'].astype('category')

In [83]:
fruits_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruits, dtype: category
Categories (2, object): ['apple', 'orange']

now fruits_cat is instance of pandas.Categorical. Now we can access by using .array attribute

In [87]:
c=fruits_cat.array # here .array is attribute
type(c)

pandas.core.arrays.categorical.Categorical

Categorical object have two attributes one is categories and another one is codes

In [88]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [89]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [90]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

we can convert dataframe column into categorical by assigning result

In [93]:
df['fruits']=df['fruits'].astype('category')

In [ ]:
df['fruits']

we can create directly pandas.Categorical by other python sequences

In [95]:
my_categories=pd.Categorical(['foo','bar','baz','foo','bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [101]:
categories=['foo','bar','baz']
codes=[0,1,1,2,0,2,1]

In [103]:
my_cat=pd.Categorical.from_codes(codes,categories)
my_cat

['foo', 'bar', 'bar', 'baz', 'foo', 'baz', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [105]:
# we ordering categorical data explict
my_cate_ordered=pd.Categorical.from_codes(codes,categories,ordered=True)
my_cate_ordered

['foo', 'bar', 'bar', 'baz', 'foo', 'baz', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [106]:
# we can ordered
my_cat_ordered=my_cat.as_ordered()
my_cat_ordered

['foo', 'bar', 'bar', 'baz', 'foo', 'baz', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [107]:
# Computational with categorical data
rng=np.random.default_rng(seed=12344)
draws=rng.standard_normal(1000)
draws[:5]


array([ 1.35175252,  1.33845148,  0.9388041 , -0.5367456 ,  0.96219857])

In [108]:
bins=pd.cut(draws,4)
bins

[(-0.242, 1.44], (-0.242, 1.44], (-0.242, 1.44], (-1.923, -0.242], (-0.242, 1.44], ..., (-1.923, -0.242], (-1.923, -0.242], (-1.923, -0.242], (-1.923, -0.242], (-0.242, 1.44]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.611, -1.923] < (-1.923, -0.242] < (-0.242, 1.44] <
                                           (1.44, 3.121]]

In [109]:
# here we adding labels to for better understand
bins=pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

['Q4', 'Q4', 'Q4', 'Q2', 'Q4', ..., 'Q1', 'Q2', 'Q1', 'Q1', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [111]:
bins.codes[:10]

array([3, 3, 3, 1, 3, 1, 2, 2, 1, 3], dtype=int8)

In [113]:
bins=pd.Series(bins,name='quartile')
results=(pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())
results

quartile  count       min       max
0       Q1    250 -3.604314 -0.657300
1       Q2    250 -0.649140  0.032486
2       Q3    250  0.036919  0.657327
3       Q4    250  0.659584  3.121017

In [115]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [117]:
# Better performance with categorical
N=10_00_000
labels=pd.Series(['foo','bar','baz','qux']*(N//4))
# now labels converted into categories
categories=labels.astype('category')
categories

0         foo
1         bar
2         baz
3         qux
4         foo
         ... 
999995    qux
999996    foo
999997    bar
999998    baz
999999    qux
Length: 1000000, dtype: category
Categories (4, object): ['bar', 'baz', 'foo', 'qux']

In [124]:
# to calculate memory capacity for both labels and categories
label_memory=labels.memory_usage(deep=True)
label_memory

60000128

In [123]:
categories_memory=categories.memory_usage(deep=True)
categories_memory

1000540

In [130]:
%time _ = labels.astype('category')
%time _

CPU times: user 35.3 ms, sys: 4.07 ms, total: 39.4 ms
Wall time: 40.8 ms
CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 3.1 µs


0         foo
1         bar
2         baz
3         qux
4         foo
         ... 
999995    qux
999996    foo
999997    bar
999998    baz
999999    qux
Length: 1000000, dtype: category
Categories (4, object): ['bar', 'baz', 'foo', 'qux']

In [131]:
%timeit labels.value_counts()

45.3 ms ± 9.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [132]:
%timeit categories.value_counts()

2.23 ms ± 124 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [136]:
# categorical Methods
s=pd.Series(['a','b','c','d']*2)
cat_s=s.astype('category')
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [137]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [138]:
actual_categories=['a','b','c','d','e']
cat_s2=cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [139]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [140]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In large datasets, categoricals are often used as a convenient tool for memory savings and better performance. After you filter a large DataFrame or Series, many of the categories may not appear in the data. To help with this, we can use the remove_unused_categories method to trim unobserved categories:

In [148]:
cat_s3=cat_s[cat_s.isin(['a','b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [150]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [151]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [155]:
# creating dummy variables
cat_s=pd.Series(['a','b','c','d']*2,dtype='category')
pd.get_dummies(cat_s,dtype=float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0