In [ ]:
import numpy as np

# data=np.array([[1,2,3,4],[5,6,7,8]])
# print(data)
# print(data.ndim) # 2
# print(data.shape) # (2,4)

# manipulate array
# data=data*2
# print(data) # [[ 2  4  6  8] [10 12 14 16]]

# data=data+data
# print(data) # [[ 4  8 12 16] [20 24 28 32]]

# find datatype
# print(data.dtype) # int32

# creating nd arrays
# data1 = [6, 7.5, 8, 0, 1]
# arr1=np.array(data1)
# print(arr1)

# 2D
# data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
# arr2=np.array(data2)
# dtype or datatype
# print(arr1.dtype) # float64
# print(arr2.dtype) # int32
# print(arr2)

# other numpy functions

# arr3=np.zeros(3)
# print(arr3) # [0. 0. 0.]

# arr3=np.zeros((2,3))
# print(arr3) # [[0. 0. 0.] [0. 0. 0.]]

# arr3=np.empty((2,3,2))
# print(arr3)

# numpy have arange function like python have range
# arr4=np.arange(10)
# print(arr4) # [0 1 2 3 4 5 6 7 8 9]
# arr4_dum=np.asarray(arr4)
# print(type(arr4))
# print(arr4_dum)
# datetypes for ndarray

# arr1=np.array([1,2,3],dtype=np.float64)
# print(arr1.dtype) # float64
#
# arr2=np.array([1,2,3],dtype=np.int32)
# print(arr2.dtype) # int32

# type casting or change data type into another data type
# arr = np.array([1, 2, 3, 4, 5])
# print(arr.dtype) # int32

# int to float
# float_arr=arr.astype(np.float64)
# print(float_arr.dtype) # float64
# print(float_arr) # [1. 2. 3. 4. 5.]

# float to int
# arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
# print(arr.dtype) # float64
# print(arr) # [ 3.7 -1.2 -2.6  0.5 12.9 10.1]

#  If I cast some floating-point numbers to be of integer data type,
#  the decimal part will be truncated:

# int_arr=arr.astype(np.int32)
# print(int_arr.dtype) # int32
# print(int_arr) # [ 3 -1 -2  0 12 10]

# convert array of string numbers into numberic value

# numeric_strings=np.array(['1','2','3.','4'],dtype=np.string_)
# print(numeric_strings.dtype) # |S2
# print(numeric_strings) # [b'1' b'2' b'3.' b'4']

# numberic=numeric_strings.astype(np.float64)
# print(numberic.dtype) # float64
# print(numberic) # [1. 2. 3. 4.]

# convert data type into existing data type by using variable
# int_array=np.arange(10)
# calibers=np.array([.22,.34,.23,.56,.78,.32],dtype=np.float64)
# print(int_array) # [0 1 2 3 4 5 6 7 8 9]
# way 1
# float_array=int_array.astype(np.float64)
# way 2
# float_array=int_array.astype(calibers.dtype)
# print(float_array) # [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

#
# zero_uint32=np.zeros(8,dtype='u4')
# print(zero_uint32) # [0 0 0 0 0 0 0 0]
# print(zero_uint32.dtype)

# Arithmetic with NumPy Arrays

# arr=np.array([[1,2,3],[4,5,6]])
# arr=arr*arr
# print(arr) # [[ 1  4  9] [16 25 36]]

# arr=arr-arr
# print(arr) # [[0 0 0] [0 0 0]]

# arr=1/arr
# print(arr)

# arr=arr**2
# print(arr)

# comparison between arr1 & arr2
# arr1=np.array([[1,2,3],[4,5,6]])
# arr2=np.array([[7,8,9],[2,4,9]])
# result=arr1<arr2
# print(result) # [[ True  True  True] [False False  True]]

# Basic Indexing and Slicing
# indexing
# arr=np.arange(10)
# print(arr[2]) # 2
# print(arr[-1]) # 9

# slicing => slice we can view the orginal arrays
# arr = np.arange(10)
# arr[1]=12345
# print(arr)
# print(arr[1:4]) # [1 2 3]

# to get all slice values [:]
# print(arr[:]) # [0 1 2 3 4 5 6 7 8 9]

# by default slice cant copy the value
# print(arr[1:4]) # [1 2 3]

# if you want copy the slice values then we need to use copy()
# copy_slice=arr[1:3].copy()
# print(copy_slice) # [1 2]

# 2D
# arr2d=np.array([[1,2,3,4],[5,6,7,8]])
# print(arr2d[0]) # [1 2 3 4]

# accessing individual elements
# print(arr2d[0,2]) # 3
# print(arr2d[1,2]) # 7

# In multidimensional arrays, if you omit later indices,
# the returned object will be a lower dimensional ndarray consisting of -
# all the data along the higher dimensions.
# So in the 2 × 2 × 3 array arr3d:

# arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# old_arr=arr3d[0].copy()
# arr3d[0]=28
# print(arr3d)

# arr3d[0]=old_arr
# print(arr3d)

# indexing
# x=arr3d[1]
# print(x[0])

# Indexing with slices
# 1D
# arr=np.array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])
# print(arr) # [ 0  1  2  3  4 64 64 64  8  9]

# indexing 1D
# print(arr[1:4]) # [1 2 3]

# 2D
# arr2d = np.array([[1, 2, 3],
#                   [4, 5, 6],
#                   [7, 8, 9]])

# print(arr2d[:2]) # [[1 2 3] [4 5 6]]
# multiple slices
# print(arr2d[:2,1:]) # [[2 3][5 6]]

# 2nd row, first two columns
# lower_dimen_slice=arr2d[1,:2] # [ 4 5]
# print(lower_dimen_slice.shape) # (2,)

# third column and first two rows
# print(arr2d[:2,2]) # [3 6]

# first column and three rows
# print(arr2d[:,:1]) # [[1] [4] [7]]

# assigning expression to whole value
# arr2d[:2,1:3]=0
# print(arr2d) # [[1 0 0] [4 0 0] [7 8 9]]

# Boolean Indexing
# names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
# data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

# print(names.dtype) # <U4
# print(names=='Bob') # [ True False False  True False False False]
# Boolean array can b   e passed when indexing the array:
# print(data[names=='Bob']) # [[4 7] [0 0]]

# print(data[names=='Bob',1:]) # [[7] [0]]
# print(data[names=='Bob',1]) # [ 7 0 ]

# both are same => names!='Bob' | ~(names=='Bob'

# print(names!='Bob') # [False  True  True False  True  True  True]
# print(~(names=='Bob')) # [False  True  True False  True  True  True]

# indexing that not have Bob name
# print(data[~(names=='Bob')]) # [[  0   2] [ -5   6] [  1   2] [-12  -4] [  3   4]]

# ~ opeartor can be useful when you want invert boolean array referenced by variable
# cond=[names=='Bob']
# print(data[~cond])

# select two of the three names to combine multiple Boolean conditions,
# use Boolean arithmetic operators like & (and) and | (or)

# mask = (names == 'Bob') | (names == 'Will')
# print(mask) # [ True False  True  True  True False False]

# print(data[mask]) # [[ 4  7] [-5  6] [ 0  0] [ 1  2]]
# data[data < 0] = 0
# print(data)  # [[4 7][0 2][0 6][0 0][1 2][0 0][3 4]]

# we can set whole rows or columns value
# data[~(names == 'Joe')] = 7
# print(data)  # [[7 7][0 2][7 7][7 7][7 7][0 0][3 4]]

# Fancy Indexing
# arr=np.zeros((8,4))
# for i in range(8):
#     arr[i]=i
# print(arr)

# print(arr[[4,3,0,6]])
# /*
# [[4. 4. 4. 4.]
#  [3. 3. 3. 3.]
#  [0. 0. 0. 0.]
#  [6. 6. 6. 6.]]
# */
#

# negative indexes
# print(arr[[-3,-5,-7]])
# /*
# [[5. 5. 5. 5.]
#  [3. 3. 3. 3.]
#  [1. 1. 1. 1.]]
# */

# arr=np.arange(32).reshape(8,4)
# print(arr)
# /*
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]
#  [16 17 18 19]
#  [20 21 22 23]
#  [24 25 26 27]
#  [28 29 30 31]]
# */
# print(arr[[1, 5, 7, 2], [0, 3, 1, 2]]) # [4 23 29 10]
# arr[[1, 5, 7, 2], [0, 3, 1, 2]]=0
# print(arr)
# /*
# [ 0  5  6  7]
#  [ 8  9  0 11]
#  [12 13 14 15]
#  [16 17 18 19]
#  [20 21 22  0]
#  [24 25 26 27]
#  [28  0 30 31]]
# */


# Transposing Arrays and Swapping Axes
# arr = np.arange(15).reshape(3, 5)
# print(arr)
# */
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]
# /*
# => arrays have transpose method special attribute T
# print(arr.T)
# */
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]
# /*

# continue previous example concept
# arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
# print(arr)
# */
# [[ 0  1  0]
#  [ 1  2 -2]
#  [ 6  3  2]
#  [-1  0 -1]
#  [ 1  0  1]]
# /*

# trans_result=np.dot(arr.T,arr)
# print(trans_result)
# */
# [[39 20 12]
#  [20 14  2]
#  [12  2 10]]
# /*
# we can do this same way like by using @ infinx operator
# print(arr.T @ arr)
# */
# [[39 20 12]
#  [20 14  2]
#  [12  2 10]]
# /*

# Simple transposing with .T is a special case of swapping axes. ndarray has the method swapaxes,
# which takes a pair of axis numbers and switches the indicated axes to rearrange the data:

# swapaxes similarly returns a view on the data without making a copy.

# print(arr)
# */
# [[ 0  1  0]
#  [ 1  2 -2]
#  [ 6  3  2]
#  [-1  0 -1]
#  [ 1  0  1]]
# /*

# print(arr.swapaxes(0,1))
# */
# [[ 0  1  6 -1  1]
#  [ 1  2  3  0  0]
#  [ 0 -2  2 -1  1]]
# /*

# Pseudorandom Number Generation

# samples=np.random.standard_normal(size=(4,4))
# print(samples)
# */
# [[ 0.04325162 -0.29336536 -0.19202156 -0.4182856 ]
#  [-1.35561233 -0.41165944 -0.89991051  1.51243871]
#  [-0.65093795  2.31260969  0.05338311  0.20138623]
#  [ 0.18536079 -0.72177461 -0.83052679 -1.37517864]]
# /*

# rng=np.random.default_rng(seed=12345)
# data = rng.standard_normal((2,3))
# print(data)
# */
# [[-1.42382504  1.26372846 -0.87066174]
#  [-0.25917323 -0.07534331 -0.74088465]]
# /*
# print(type(rng)) # <class 'numpy.random._generator.Generator'>

# pseudo random number generation:
# */
# random number is not getting same number again and again. Random number means that we cannot predict the number
# but we can control the random number by using pseudo random number technique.
# /*

# this is youtube person explain the random number generation
# np.random.seed(0) # we can set random number fixed by using seed method
# x=np.random.randint(1,7,size=3)
# print(x)


# Universal Functions: Fast Element-Wise Array Functions

# arr=np.arange(10)
# print(arr) # [0 1 2 3 4 5 6 7 8 9]

# print(np.sqrt(arr))
# */
# [0.   1.   1.41421356 1.73205081   2.   2.23606798
#  2.44948974 2.64575131 2.82842712 3.        ]
# /*
# print(np.exp(arr))
# */
# [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
#  5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
#  2.98095799e+03 8.10308393e+03]
# /*

# rng=np.random.default_rng(seed=12345)
# x=rng.standard_normal(8)
# print(x)
# */
# [-1.42382504  1.26372846 -0.87066174 -0.25917323 -0.07534331 -0.74088465
#  -1.3677927   0.6488928 ]
# /*
# y=rng.standard_normal(8)
# print(y)
# */
# [ 0.36105811 -1.95286306  2.34740965  0.96849691 -0.75938718  0.90219827
#  -0.46695317 -0.06068952]
# /*
# print(np.maximum(x,y))
# */
# [ 0.36105811  1.26372846  2.34740965  0.96849691 -0.07534331  0.90219827
#  -0.46695317  0.6488928 ]
# /*

#  ufunc can return multiple arrays numpy.modf is one example,
# vectorised version of build in python math.modf, it returns the frictional and integral parts of a floating point array
# rng = np.random.default_rng(seed=12345)
# arr = rng.standard_normal(7) * 5
# print(arr)
# */
# [-7.11912518  6.31864229 -4.35330869 -1.29586617 -0.37671654 -3.70442326 -6.83896351]
# /*

# remainder, whole_part = np.modf(arr)
# print(remainder)
# */
# [-0.11912518  0.31864229 -0.35330869 -0.29586617 -0.37671654 -0.70442326
#  -0.83896351]
# /*#
# print(whole_part) # [-7.  6. -4. -1. -0. -3. -6.]

# Ufuncs accept an optional out argument that allows them to assign their results into existing array rather than -
# create a new one

# out = np.zeros_like(arr)

# print(out) # [0. 0. 0. 0. 0. 0. 0.]

# print(arr) # [-7.11912518  6.31864229 -4.35330869 -1.29586617 -0.37671654 -3.70442326 -6.83896351]

# print(np.add(arr,1)) # [-6.11912518  7.31864229 -3.35330869 -0.29586617  0.62328346 -2.70442326 -5.83896351]

# print(np.add(arr,1,out=out)) # [-6.11912518  7.31864229 -3.35330869 -0.29586617  0.62328346 -2.70442326 -5.83896351]

# print(out) # [-6.11912518  7.31864229 -3.35330869 -0.29586617  0.62328346 -2.70442326 -5.83896351]


# Array-Oriented Programming with Arrays
# / Notes :
# Using NumPy arrays enables you to express many kinds of data processing
# tasks as concise array expressions that might otherwise require writing loops.
# This practice of replacing explicit loops with array expressions is referred to
# by some people as vectorization. In general, vectorized array operations will usually
# be significantly faster than their pure Python equivalents, with the biggest impact in
# any kind of numerical computations.
# /#

##
# As a simple example, suppose we wished to evaluate the function sqrt(x^2 + y^2) across
# a regular grid of values. The numpy.meshgrid function takes two one-dimensional arrays
# and produces two two-dimensional matrices corresponding to all pairs of (x, y) in the two arrays:
# ##

# points = np.arange(-5, 5, 0.01)
# print(points) # # 100 equally spaced points

# xs, ys = np.meshgrid(points, points)

# print(xs)
##
# [[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
#  [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
#  [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
#  ...
#  [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
#  [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
#  [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
# ##
# print(ys)
##

# [[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
#  [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
#  [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
#  ...
#  [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
#  [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
#  [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]
# ##

# Now, evaluating the function is a matter of writing the same expression you would write with two points:

# z = np.sqrt(xs ** 2 + ys ** 2)
# print(z)

# Expressing Conditional Logic as Array Operations

# xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

# yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

# cond = np.array([True, False, True, True, False])

# result=[x if z else y for x,y,z in zip(xarr,yarr,cond)]
# print(result) # [1.1, 2.2, 1.3, 1.4, 2.5]

# limitations
##
# This has multiple problems. First, it will not be very fast for large
# arrays (because all the work is being done in interpreted Python code).
# Second, it will not work with multidimensional arrays. With numpy.where you
# can do this with a single function call:
# ##

# result=np.where(cond,xarr,yarr)
# print(result) # [1.1 2.2 1.3 1.4 2.5]

# arr=rng.standard_normal((4,4))
# print(arr)
##
# [[ 0.6488928   0.36105811 -1.95286306  2.34740965]
#  [ 0.96849691 -0.75938718  0.90219827 -0.46695317]
#  [-0.06068952  0.78884434 -1.25666813  0.57585751]
#  [ 1.39897899  1.32229806 -0.29969852  0.90291934]]
# ##
# print(arr>0)
##
# [[ True  True False  True]
#  [ True False  True False]
#  [False  True False  True]
#  [ True  True False  True]]
# ##

# print(np.where(arr>0,2,-2))
##
# [[ 2  2 -2  2]
#  [ 2 -2  2 -2]
#  [-2  2 -2  2]
#  [ 2  2 -2  2]]
# ##

# print(np.where(arr>0,2,arr))
##
# [[ 2.          2.         -1.95286306  2.        ]
#  [ 2.         -0.75938718  2.         -0.46695317]
#  [-0.06068952  2.         -1.25666813  2.        ]
#  [ 2.          2.         -0.29969852  2.        ]]
# ##


#  Mathematical and Statistical Methods

# arr=rng.standard_normal((5,4))
# print(arr)
##
# [[-1.62158273 -0.15818926  0.44948393 -1.34360107]
#  [-0.08168759  1.72473993  2.61815943  0.77736134]
#  [ 0.8286332  -0.95898831 -1.20938829 -1.41229201]
#  [ 0.54154683  0.7519394  -0.65876032 -1.22867499]
#  [ 0.25755777  0.31290292 -0.13081169  1.26998312]]
# ##

# print(arr.mean()) # 0.03641657980011391

# print(np.mean(arr)) # 0.03641657980011391

# print(np.sum(arr)) # 0.7283315960022783

# print(arr.sum()) # 0.7283315960022783

# print(arr.mean(axis=1)) # [-0.66847228  1.25964328 -0.68800885 -0.14848727  0.42740803]

# print(arr.sum(axis=0)) # [-0.07553253  1.67240467  1.06868306 -1.93722361]

# Here, arr.mean(axis=1) means “compute mean across the columns,
# ” where arr.sum(axis=0) means “compute sum down the rows.”

# arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
# print(arr.cumsum()) # [ 0  1  3  6 10 15 21 28 36]

# print(arr.cumsum(axis=0))
##
# [[ 0  1  2]
#  [ 3  5  7]
#  [ 9 12 15]]
# ##

# print(arr.cumsum(axis=1))
##
# [[ 0  1  3]
#  [ 3  7 12]
#  [ 6 13 21]]
# ##

# Methods for Boolean Arrays
# Boolean values are coerced to 1 (True) and 0 (False) in the preceding methods.
# Thus, sum is often used as a means of counting True values in a Boolean array:

# 100 pseudo random numbers
# arr=rng.standard_normal(100)
# print((arr>0).sum())# 51 for positive addition value

# print((arr<=0).sum()) # 48 for negative addition value

# bools=np.array([False,False,True,False])
# print(np.any(bools)) # True

# print(np.all(bools)) # False


# Sorting

# arr=rng.standard_normal(6)
# print(arr) # [-0.6733048   1.24622153  0.79020803  0.17534089 -0.0292946  -1.41951426]

# arr.sort()
# print(arr) # [-1.42382504 -0.87066174 -0.74088465 -0.25917323 -0.07534331  1.26372846]

# You can sort each one-dimensional section of values in a multidimensional array in place
# along an axis by passing the axis number to sort. In this example data:

# arr=rng.standard_normal((5,3))
# print(arr)
##
# [[-1.42382504  1.26372846 -0.87066174]
#  [-0.25917323 -0.07534331 -0.74088465]
#  [-1.3677927   0.6488928   0.36105811]
#  [-1.95286306  2.34740965  0.96849691]
#  [-0.75938718  0.90219827 -0.46695317]]
# ##

# arr.sort(axis=0) # axis=0 means sorting the column values
# print(arr)
##
# [[-1.95286306 -0.07534331 -0.87066174]
#  [-1.42382504  0.6488928  -0.74088465]
#  [-1.3677927   0.90219827 -0.46695317]
#  [-0.75938718  1.26372846  0.36105811]
#  [-0.25917323  2.34740965  0.96849691]]
# ##

# arr.sort(axis=1)
# print(arr)
##
# [[-1.42382504 -0.87066174  1.26372846]
#  [-0.74088465 -0.25917323 -0.07534331]
#  [-1.3677927   0.36105811  0.6488928 ]
#  [-1.95286306  0.96849691  2.34740965]
#  [-0.75938718 -0.46695317  0.90219827]]
# ##

# The top-level method numpy.sort returns a sorted copy of an array
# (like the Python built-in function sorted) instead of modifying the array in place. For example:

# arr2 = np.array([5, -10, 7, 1, 0, -3])
# print(np.sort(arr2)) # [-10  -3   0   1   5   7]


# Unique and Other Set Logic:
# NumPy has some basic set operations for one-dimensional ndarrays.
# A commonly used one is numpy.unique, which returns the sorted unique values in an array:

# names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
# print(np.unique(names)) # ['Bob' 'Joe' 'Will']

# ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
# print(np.unique(ints)) # [1 2 3 4]

# Contrast numpy.unique with the pure Python alternati
# print(sorted(set(names))) # ['Bob', 'Joe', 'Will']

# values = np.array([6, 0, 0, 3, 2, 5, 6])
# result=np.in1d(values,[2,3,6])
# print(result) # [ True False False  True  True False  True]

# File Input and Output with Arrays

# arr=np.arange(10)
# np.save('some_array',arr)
# print(arr) # [0 1 2 3 4 5 6 7 8 9]

# np.load('some_array.npy')
# print(arr) # [0 1 2 3 4 5 6 7 8 9]

# np.savez('array_archive.npz',a=arr,b=arr)

# arch=np.load('array_archive.npz')
# print(arch['b'])

# If your data compresses well, you may wish to use numpy.savez_compressed instead:

# arch_2=np.savez_compressed('arrays_uncompressed.npz',a=arr,b=arr)


# Linear Algebra

# => Linear algebra operations, like matrix multiplication, decompositions, determinants,
# and other square matrix math, are an important part of many array libraries

# => Multiplying two two-dimensional arrays with * is an element-wise product, while matrix multiplications
# require using a function. Thus, there is a function dot, both an array method and a function in the numpy namespace,
# for matrix multiplication:
#

# x = np.array([[1., 2., 3.], [4., 5., 6.]])

# y = np.array([[6., 23.], [-1, 7], [8, 9]])

# print(x)
# [[1. 2. 3.]
#  [4. 5. 6.]]
# print(y)
# [[ 6. 23.]
#  [-1.  7.]
#  [ 8.  9.]]

# print(x.dot(y))
# [[ 28.  64.]
#  [ 67. 181.]]

# x.dot(y) is equivalent to np.dot(x, y):

# print(np.dot(x,y))
# [[ 28.  64.]
#  [ 67. 181.]]

# Example: Random Walks
#   --->  :(  <---

