In [ ]:
from operator import index

import pandas as pd
import numpy as np

from pandas import DataFrame, Series

obj = pd.Series([4, 7, -5, 3])
# print(obj)
# */
# 0    4
# 1    7
# 2   -5
# 3    3
# dtype: int64
# /*
# print(obj.array)
##
# <PandasArray>
# [4, 7, -5, 3]
# Length: 4, dtype: int64
# ##
# print(obj.index) # RangeIndex(start=0, stop=4, step=1)

# Often, you’ll want to create a Series with an index identifying each data point with a label:
obj2 = pd.Series([4, 7, -5, 3], index=('d', 'b', 'a', 'c'))
# print(obj2)
##
# d    4
# b    7
# a   -5
# c    3
# dtype: int64
# ##
# print(obj2.index) # Index(['d', 'b', 'a', 'c'], dtype='object')

# access the values by using index values
# print(obj2['a']) # -5

# print(obj2['b']) # 7

# print(obj2[['c','a','d']])
##
# c    3
# a   -5
# d    4
# dtype: int64
# ##

# print(obj2[obj2>0])
##
# d    4
# b    7
# c    3
# dtype: int64
# ##

# print(obj2*2)
##
# d     8
# b    14
# a   -10
# c     6
# dtype: int64
# ##

# print(np.exp(obj2))
##
# d      54.598150
# b    1096.633158
# a       0.006738
# c      20.085537
# dtype: float6
# ##

# print('b' in obj2) # True
# print('j' in obj2) # False

# we can convert into dictionary into series
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
# print(obj3)
##
# Ohio      35000
# Texas     71000
# Oregon    16000
# Utah       5000
# dtype: int64
# ##

# we can convert into pandas Series into dictionary
# print(obj3.to_dict()) # {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}


states = ["California", "Ohio", "Oregon", "Texas"]
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj4 = pd.Series(sdata, index=states)
# print(obj4)
##
# California        NaN
# Ohio          35000.0
# Oregon        16000.0
# Texas         71000.0
# dtype: float64
# ##

# print(pd.isna(obj4))
##
# California     True
# Ohio          False
# Oregon        False
# Texas         False
# dtype: bool
# ##

# print(pd.notna(obj4))
##
# California    False
# Ohio           True
# Oregon         True
# Texas          True
# dtype: bool
# ##

# Series also has these as instance methods:
# print(obj4.isna())
##
# California     True
# Ohio          False
# Oregon        False
# Texas         False
# dtype: bool
# ##

# print(obj3+obj4)
##
# California         NaN
# Ohio           70000.0
# Oregon         32000.0
# Texas         142000.0
# Utah               NaN
# dtype: float64
# ##

obj4.name = 'popualtion'

obj4.index.name = 'state'

# print(obj4)
##
# state
# California        NaN
# Ohio          35000.0
# Oregon        16000.0
# Texas         71000.0
# Name: popualtion, dtype: float64
# ##

# print(obj)
##
# 0    4
# 1    7
# 2   -5
# 3    3
# dtype: int64
# ##

# obj.index=['Bob','Steve','Jeff','Ryan']
# print(obj)
##
# Bob      4
# Steve    7
# Jeff    -5
# Ryan     3
# dtype: int64
# ##

# DataFrame => rectangular table of data and contains an ordered , named collection of columns
# There are many ways to construct a DataFrame,
# though one of the most common is from a dictionary of equal-length lists or NumPy arrays:

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Neveda', 'Neveda', 'Neveda'],
        'year': ['2000', '2001', '2002', '2001', '2002', '2003'],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
        }

frame = pd.DataFrame(data)
# print(frame)
##
#    state  year  pop
# 0    Ohio  2000  1.5
# 1    Ohio  2001  1.7
# 2    Ohio  2002  3.6
# 3  Neveda  2001  2.4
# 4  Neveda  2002  2.9
# 5  Neveda  2003  3.2
# ##

# head method returns first five rows
# print(frame.head())
##
#     state  year  pop
# 0    Ohio  2000  1.5
# 1    Ohio  2001  1.7
# 2    Ohio  2002  3.6
# 3  Neveda  2001  2.4
# 4  Neveda  2002  2.9
# ##

# similarly tail method returns last 5 rows
# print(frame.tail())
##
# 1    Ohio  2001  1.7
# 2    Ohio  2002  3.6
# 3  Neveda  2001  2.4
# 4  Neveda  2002  2.9
# 5  Neveda  2003  3.2
# ##

# If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order
# print(pd.DataFrame(data,columns=['year','state','pop']))
##
#   year   state  pop
# 0  2000    Ohio  1.5
# 1  2001    Ohio  1.7
# 2  2002    Ohio  3.6
# 3  2001  Neveda  2.4
# 4  2002  Neveda  2.9
# 5  2003  Neveda  3.2
# ##

# If you pass a column that isn’t contained in the dictionary, it will appear with missing values in the result:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])
# print(frame2)
##
#    year   state mess  pop
# 0  2000    Ohio  NaN  1.5
# 1  2001    Ohio  NaN  1.7
# 2  2002    Ohio  NaN  3.6
# 3  2001  Neveda  NaN  2.4
# 4  2002  Neveda  NaN  2.9
# 5  2003  Neveda  NaN  3.2
# ##


# print(frame2.columns) # Index(['year', 'state', 'mess', 'pop'], dtype='object')

# A column in a DataFrame can be retrieved as a Series either by dictionary-like notation or
# by using the dot attribute notation:
# print(frame2['state'])
##
# 0      Ohio
# 1      Ohio
# 2      Ohio
# 3    Neveda
# 4    Neveda
# 5    Neveda
# Name: state, dtype: object
# ##

# print(frame2.year)
##
# 0    2000
# 1    2001
# 2    2002
# 3    2001
# 4    2002
# 5    2003
# Name: year, dtype: object
# ##

# rows can accessed by loc and iloc
# print(frame2.loc[5])
##
# year       2003
# state    Neveda
# mess        NaN
# pop         3.2
# Name: 5, dtype: object
# #

# rows can accessed by loc and iloc
# print(frame2.iloc[5])
##
# year       2003
# state    Neveda
# mess        NaN
# pop         3.2
# Name: 5, dtype: object
# #

# Columns can be modified by assignment
# frame2['debt']=16.5
# print(frame2)
##
#    year   state  pop  debt
# 0  2000    Ohio  1.5  16.5
# 1  2001    Ohio  1.7  16.5
# 2  2002    Ohio  3.6  16.5
# 3  2001  Neveda  2.4  16.5
# 4  2002  Neveda  2.9  16.5
# 5  2003  Neveda  3.2  16.5
# #

# frame2['debt']=np.arange(6.)
# print(frame2)
##
#    year   state  pop  debt
# 0  2000    Ohio  1.5   0.0
# 1  2001    Ohio  1.7   1.0
# 2  2002    Ohio  3.6   2.0
# 3  2001  Neveda  2.4   3.0
# 4  2002  Neveda  2.9   4.0
# 5  2003  Neveda  3.2   5.0
# #

# When you are assigning lists or arrays to a column, the value’s length must match the length of the DataFrame.
# If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, inserting missing values-
# in any index values not present:

val = pd.Series([-1.2, -1.5, -1.7, 1.8, 1.9, 1.4], index=('two', 'four', 'five', 'six', 'seven', 'eight'))
# print(val)
# frame2['debt']=val
# print(frame2)
##
#    year   state  pop  debt
# 0  2000    Ohio  1.5   NaN
# 1  2001    Ohio  1.7   NaN
# 2  2002    Ohio  3.6   NaN
# 3  2001  Neveda  2.4   NaN
# 4  2002  Neveda  2.9   NaN
# 5  2003  Neveda  3.2   NaN
# #

# The del keyword will delete columns like with a dictionary.
# As an example, I first add a new column of Boolean values where the state column equals "Ohio"

frame2['eastern'] = frame2['state'] == 'Ohio'
# print(frame2)
##
#    year   state  pop debt  eastern
# 0  2000    Ohio  1.5  NaN     True
# 1  2001    Ohio  1.7  NaN     True
# 2  2002    Ohio  3.6  NaN     True
# 3  2001  Neveda  2.4  NaN    False
# 4  2002  Neveda  2.9  NaN    False
# 5  2003  Neveda  3.2  NaN    False
# #

# new columns connot created by using dot attribute notation
# frame2.category='empty'

# using del method we can remove column easily
# del(frame2['eastern'])
# print(frame2)
##
#    year   state  pop debt
# 0  2000    Ohio  1.5  NaN
# 1  2001    Ohio  1.7  NaN
# 2  2002    Ohio  3.6  NaN
# 3  2001  Neveda  2.4  NaN
# 4  2002  Neveda  2.9  NaN
# 5  2003  Neveda  3.2  Na
# #

# another common form of nested dictionaries:

populations = {'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
# print(frame3)
##
#       Ohio  Nevada
# 2000   1.5     NaN
# 2001   1.7     2.4
# 2002   3.6     2.9
# #

# we can transpose the DataFrame
# print(frame3.T)
##
#         2000  2001  2002
# Ohio     1.5   1.7   3.6
# Nevada   NaN   2.4   2.9
# #

# print(pd.DataFrame(populations,index=(2001,2002,2003)))
##
#       Ohio  Nevada
# 2001   1.7     2.4
# 2002   3.6     2.9
# 2003   NaN     NaN
# #

# Dictionaries of Series are treated in much the same way
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
# print(pd.DataFrame(pdata))
##
#       Ohio  Nevada
# 2000   1.5     NaN
# 2001   1.7     2.4
# #

frame3.index.name = 'year'
frame3.columns.name = 'state'
# print(frame3)
##
# state  Ohio  Nevada
# year
# 2000    1.5     NaN
# 2001    1.7     2.4
# 2002    3.6     2.9
# #

# Unlike Series, DataFrame does not have a name attribute.
# DataFrame’s to_numpy method returns the data contained in the DataFrame as a two-dimensional ndarray:

# print(frame3.to_numpy()) # it gives 2D array
##
# [[1.5 nan]
#  [1.7 2.4]
#  [3.6 2.9]]
# ##

# print(frame2.to_numpy())
##
# [['2000' 'Ohio' 1.5 nan True]
#  ['2001' 'Ohio' 1.7 nan True]
#  ['2002' 'Ohio' 3.6 nan True]
#  ['2001' 'Neveda' 2.4 nan False]
#  ['2002' 'Neveda' 2.9 nan False]
#  ['2003' 'Neveda' 3.2 nan False]]
# #

# Index Objects
# pandas’s Index objects are responsible for holding the axis labels (including a DataFrame’s column names)
# and other metadata (like the axis name or names). Any array or other sequence of labels you use when constructing
# a Series or DataFrame is internally converted to an Index:

obj = pd.Series(np.arange(3), index=['a', 'b', 'c'])
index = obj.index
# print(index) # Index(['a', 'b', 'c'], dtype='object')
# print(index[1:]) # Index(['b', 'c'], dtype='object')

# Index objects are immutable cant't modified by user
# index[1]='J'
# print(index) # Index does not support mutable operations

# Immutability makes it safer to share Index objects among data structures:

labels = pd.Index(np.arange(3))
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
# print(obj2)
##
# 0    1.5
# 1   -2.5
# 2    0.0
# dtype: float64
# #

# print(obj2.index is labels) # True

# In addition to being array-like, an Index also behaves like a fixed-size set:
# print(frame3)
##
# state  Ohio  Nevada
# year
# 2000    1.5     NaN
# 2001    1.7     2.4
# 2002    3.6     2.9
# #

# print(frame3.columns) # Index(['Ohio', 'Nevada'], dtype='object', name='state')

# print('Ohio' in frame3.columns) # True
# print(2003 in frame3.columns) # False

# unlike puthon sets , pandas index can have duplicate values

# duplicate_idx=pd.Index(['aa','bb','cc','bb','aa'])
# print(duplicate_idx) # Index(['aa','bb','cc','bb','aa'], dtype='object')

# Essential functinality

# Reindexing
# ------------
# An important method on pandas objects is reindex, which means to create a new object
# with the values rearranged to align with the new index.

# Consider an example:
# obj=pd.Series([4.5, 7.2, -5.3, 3.6],index=['d','b','a','c'])
# print(obj)
##
# b    7.2
# a   -5.3
# c    3.6
# dtype: float64)
# #

# obj2=obj.reindex(['a','b','c','d','e'])
# print(obj2)
##
# a   -5.3
# b    7.2
# c    3.6
# d    4.5
# e    NaN   # if we did't find reindex value in actual index method will return NaN
# dtype: float64
# #

# obj3=pd.Series(['blue','purple','yellow'],index=(0,2,4))
# print(obj3)
##
# 0      blue
# 2    purple
# 4    yellow
# dtype: object
# #

# print(obj3.reindex(np.arange(8),method='ffill'))
##
# 0      blue
# 1      blue
# 2    purple
# 3    purple
# 4    yellow
# 5    yellow
# dtype: object
# #

# with DataFrame , reindex can alter rows(index), columns or both
# when passed only sequence , it reindexes of the rows results
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

# print(frame)
##
#    Ohio  Texas  California
# a     0      1           2
# c     3      4           5
# d     6      7           8
# #

frame2 = frame.reindex(['a', 'b', 'c', 'd'])
# print(frame2)
##
#     Ohio  Texas  California
# a   0.0    1.0         2.0
# b   NaN    NaN         NaN
# c   3.0    4.0         5.0
# d   6.0    7.0         8.0
# #

# columns can be reindexed thorugh the columns keyword
state = ['Texas', 'utha', 'California']
# print(frame.reindex(columns=state))
##
#    Texas  utha  California
# a      1   NaN           2
# c      4   NaN           5
# d      7   NaN           8
# #

# because of Ohio is not prsent in state. So data that column is dropped

# another way we can reindexed by using axis argumenet

# print(frame.reindex(state,axis='columns'))
##
#    Texas  utha  California
# a      1   NaN           2
# c      4   NaN           5
# d      7   NaN           8
# #

#  you can also reindex by using the loc operator, and many users prefer to always do it this way.
#  This works only if all of the new index labels already exist in the DataFrame
#  (whereas reindex will insert missing data for new labels):
# print(frame)
##
#    Ohio  Texas  California
# a     0      1           2
# c     3      4           5
# d     6      7           8
# #
# print(frame.loc[['a','d','c'],['California','Texas']])
##
#    California  Texas
# a           2      1
# d           8      7
# c           5      4
# #


# Dropping Entries from an Axis

obj = pd.Series(np.arange(6), index=['a', 'b', 'c', 'd', 'e', 'f'])
# print(obj)
##
# a    0
# b    1
# c    2
# d    3
# e    4
# f    5
# dtype: int32
# #

new_obj = obj.drop('c')
# print(new_obj)
##
#
# a    0
# b    1
# d    3
# e    4
# f    5
# dtype: int32
# #

# print(obj.drop(['a','b','c','d']))
##
# e    4
# f    5
# dtype: int32
# #

# with dataframe, index values can be deleted from either axis. To illustrate this lets consider below example
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four']
                    )

# print(data)
##
#           one  two  three  four
# Ohio        0    1      2     3
# Colorado    4    5      6     7
# Utah        8    9     10    11
# New York   12   13     14    15
# #

# print(data.drop(index=['Ohio','Utah']))
##
#           one  two  three  four
# Colorado    4    5      6     7
# New York   12   13     14    15
# #

# print(data.drop(index=['Ohio','Utah'],columns=['one','two','three']))
##
#           four
# Colorado     7
# New York    15
# #

#  we can also drop values from columns by passing axis =1
# print(data.drop(['two','four'],axis=1))
##
#           one  three
# Ohio        0      2
# Colorado    4      6
# Utah        8     10
# New York   12     14
# #

# indexing , selection and filtering

# obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
# print(obj)
##
# a    0.0
# b    1.0
# c    2.0
# d    3.0
# dtype: float64
# #
# print(obj['c']) # 2.0
# print(obj[1:3])
##
# b    1.0
# c    2.0
# dtype: float64
# #

# multiple indexing through the index value
# print(obj[['b','a','d']])
##
# b    1.0
# a    0.0
# d    3.0
# dtype: float64
# #

# multiple indexing by using numbers
# print(obj[[3,3]])
##
# d    3.0
# d    3.0
# dtype: float64
# #

# print(obj[obj<2])
##
# a    0.0
# b    1.0
# dtype: float64
# #

# iloc opeartor
# if index contains labels then we can use loc opeartor
# print(obj.loc[['b','a','d']])
##
# b    1.0
# a    0.0
# d    3.0
# dtype: float64
# #

# if index contains integers then we can indexing by using iloc operator
obj1 = pd.Series(np.arange(3), index=[1, 2, 3])
obj2 = pd.Series(np.arange(3), index=['a', 'b', 'c'])
# print(obj1)
##
# 1    0
# 2    1
# 3    2
# dtype: int32
# #
# print(obj2)
##
# a    0
# b    1
# c    2
# dtype: int32
# #

# print(obj1.loc[[1,2,3]])
##
# 2    1
# 3    2
# dtype: int32
# #

# When using loc, the expression obj.loc[[0, 1, 2]] will fail when the index does not contain integers:
# print(obj2.loc[[0,1,2]]) # it gives error

# iloc operator works both index integers and index labels
# print(obj1.iloc[[0,1,2]])
##
# 1    0
# 2    1
# 3    2
# dtype: int32
# #
# print(obj2.iloc[[0,1,2]])
##
# a    0
# b    1
# c    2
# dtype: int32
# #

# Assigning values using these methods modifies the corresponding section of the Series:
# obj2.loc['b':'c']=5
# print(obj2)
# a    0
# b    5
# c    5
# dtype: int32

# now indexing the DataFrame retreives one or more columns either single values or sequence:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four']
                    )
# print(data)
##
#           one  two  three  four
# Ohio        0    1      2     3
# Colorado    4    5      6     7
# Utah        8    9     10    11
# New York   12   13     14    15
# #

# print(data['two'])
##
# Ohio         1
# Colorado     5
# Utah         9
# New York    13
# Name: two, dtype: int32
# #

# indexing multiple values
# print(data[['one','two']])
##
#           one  two
# Ohio        0    1
# Colorado    4    5
# Utah        8    9
# New York   12   13
# #

# Indexing like this has a few special cases. The first is slicing or selecting data with a Boolean array:
# print(data[:2])
##
#           one  two  three  four
# Ohio        0    1      2     3
# Colorado    4    5      6     7
# #

# print(data[data['three']>5])
##
#           one  two  three  four
# Colorado    4    5      6     7
# Utah        8    9     10    11
# New York   12   13     14    15
# #

# print(data<5)
##
#             one    two  three   four
# Ohio       True   True   True   True
# Colorado   True  False  False  False
# Utah      False  False  False  False
# New York  False  False  False  False
# #

# data[data<5]=0
# print(data)
##
#           one  two  three  four
# Ohio        0    0      0     0
# Colorado    0    5      6     7
# Utah        8    9     10    11
# New York   12   13     14    15
##

# Selection on DataFrame with loc and iloc
# print(data.loc['Colorado'])
##
# one      4
# two      5
# three    6
# four     7
# Name: Colorado, dtype: int32
# #

# print(data.loc[['Colorado','New York']])
##
#           one  two  three  four
# Colorado    4    5      6     7
# New York   12   13     14    15
# #

# print(data.loc['Colorado',['one','two']])
##
# one    4
# two    5
# Name: Colorado, dtype: int32
# #

# iloc operator with DataFrame
# print(data.iloc[2])
##
# one       8
# two       9
# three    10
# four     11
# Name: Utah, dtype: int32
# #

# acuaring multiple columns with help of iloc
# print(data.iloc[[2,1]])
##
#           one  two  three  four
# Utah        8    9     10    11
# Colorado    4    5      6     7
# #

# print(data.iloc[2,[3,0,1]])
##
# four    11
# one      8
# two      9
# Name: Utah, dtype: int32
# #

# print(data.iloc[[1,2],[3,0,1]])
##
#           four  one  two
# Colorado     7    4    5
# Utah        11    8    9
# #

# Both indexing functions work with slices in addition to single labels or lists of labels:

# print(data.loc[:'Utah','two'])
# Ohio        1
# Colorado    5
# Utah        9
# Name: two, dtype: int32

# print(data.iloc[:,:3][data.three>11])

# print(data.loc[data.three>2])
##
#           one  two  three  four
# Colorado    4    5      6     7
# Utah        8    9     10    11
# New York   12   13     14    15
# #

# integer indexing pitfalls

ser = pd.Series(np.arange(4.0))
# print(ser)
### 0    0.0
# 1    1.0
# 2    2.0
# 3    3.0
# dtype: float64
# #

# print(ser[-1]) # value error

# in the otherhand with non integer index, there is no such ambiguity

ser1 = pd.Series(np.arange(4), index=['a', 'b', 'c', 'd'])
# print(ser1)
##
# a    0
# b    1
# c    2
# d    3
# dtype: int32
# #

# indexing last number in Series
# print(ser1[-1]) # 3

# If you have an axis index containing integers, data selection will always be label oriented.
# As I said above, if you use loc (for labels) or iloc (for integers) you will get exactly what you want:

# print(ser.iloc[-1]) # 3

# On the other hand, slicing with integers is always integer oriented:

# print(ser1[1:])
# b    1
# c    2
# d    3
# dtype: int32

# Pitfalls with chained indexing

# data.loc[:,'one']=1
# print(data)
#          one  two  three  four
# Ohio        1    1      2     3
# Colorado    1    5      6     7
# Utah        1    9     10    11
# New York    1   13     14    15

data.iloc[2] = 5
# print(data)
# Ohio        0    1      2     3
# Colorado    4    5      6     7
# Utah        5    5      5     5
# New York   12   13     14    15

data.loc[data['four'] > 5] = 3
# print(data)
##
#           one  two  three  four
# Ohio        0    1      2     3
# Colorado    3    3      3     3
# Utah        5    5      5     5
# New York    3    3      3     3
# #

data.loc[data['three'] == 5, 'three'] = 6
# print(data)
##
#           one  two  three  four
# Ohio        0    1      2     3
# Colorado    3    3      3     3
# Utah        5    5      6     5
# New York    3    3      3     3
# #


# Arithmatic and data alignment

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

# print(s1)
##
# a    7.3
# c   -2.5
# d    3.4
# e    1.5
# dtype: float64
# #

# print(s2)
##
# a   -2.1
# c    3.6
# e   -1.5
# f    4.0
# g    3.1
# dtype: float64
# #

# adding these yields
s1 + s2
# print(s1+s2)
##
# a    5.2
# c    1.1
# d    NaN
# e    0.0
# f    NaN
# g    NaN
# dtype: float64
# #

# The internal data alignment introduces missing values in the label locations that don’t overlap.
# Missing values will then propagate in further arithmetic computations.
#
# In the case of DataFrame, alignment is performed on both rows and columns:

# df1=pd.DataFrame(np.arange(9.0).reshape((3,3)),columns=list('bcd'),
#                  index=['Ohio','Texas','Colorado'])
#
# df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
#                  index=['Utah','Ohio','Texas','Oregon'])


# print(df1)
##
#             b    c    d
# Ohio      0.0  1.0  2.0
# Texas     3.0  4.0  5.0
# Colorado  6.0  7.0  8.0
# #

# print(df2)
##
#           b     d     e
# Utah    0.0   1.0   2.0
# Ohio    3.0   4.0   5.0
# Texas   6.0   7.0   8.0
# Oregon  9.0  10.0  11.0
# #

# df1+df2
# print(df1+df2)
##
#             b   c     d   e
# Colorado  NaN NaN   NaN NaN
# Ohio      3.0 NaN   6.0 NaN
# Oregon    NaN NaN   NaN NaN
# Texas     9.0 NaN  12.0 NaN
# Utah      NaN NaN   NaN NaN
# #


# If you add DataFrame objects with no column or row labels in common, the result will contain all nulls:

# df1=pd.DataFrame({'A':[1,2]})
# df2=pd.DataFrame({'B':[3,4]})
# print(df1+df2)
##
#     A   B
# 0 NaN NaN
# 1 NaN NaN
# #

# Arithmetic methods with fill values

df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

# print(df1)
#      a    b     c     d
# 0  0.0  1.0   2.0   3.0
# 1  4.0  5.0   6.0   7.0
# 2  8.0  9.0  10.0  11.0
# #
df2.loc[2, 'b'] = np.nan
# print(df2)
#       a     b     c     d     e
# 0   0.0   1.0   2.0   3.0   4.0
# 1   5.0   6.0   7.0   8.0   9.0
# 2  10.0   NaN  12.0  13.0  14.0
# 3  15.0  16.0  17.0  18.0  19.0
# #
# print(df1+df2)
##
#       a     b     c     d   e
# 0   0.0   2.0   4.0   6.0 NaN
# 1   9.0  11.0  13.0  15.0 NaN
# 2  18.0   NaN  22.0  24.0 NaN
# 3   NaN   NaN   NaN   NaN NaN
# #

# Using the add method on df1, I pass df2 and an argument to fill_value, which substitutes -
# the passed value for any missing values in the operation:

# print(df1.add(df2,fill_value=1))

# other arithmetic operations

# print(1/df1)
##
#        a         b         c         d
# 0    inf  1.000000  0.500000  0.333333
# 1  0.250  0.200000  0.166667  0.142857
# 2  0.125  0.111111  0.100000  0.090909
# #

# print(df1.rdiv(1))
#        a         b         c         d
# 0    inf  1.000000  0.500000  0.333333
# 1  0.250  0.200000  0.166667  0.142857
# 2  0.125  0.111111  0.100000  0.090909
# #

# Relatedly, when reindexing a Series or DataFrame, you can also specify a different fill value:

# print(df1.reindex(columns=df2.columns,fill_value=0))
#      a    b     c     d  e
# 0  0.0  1.0   2.0   3.0  0
# 1  4.0  5.0   6.0   7.0  0
# 2  8.0  9.0  10.0  11.0  0

# print(df1.reindex(index=df2.index,fill_value=0))
#      a    b     c     d
# 0  0.0  1.0   2.0   3.0
# 1  4.0  5.0   6.0   7.0
# 2  8.0  9.0  10.0  11.0
# 3  0.0  0.0   0.0   0.0

# Operations b/w DataFrame and Series

arr = np.arange(12.).reshape((3, 4))
# print(arr)
##
# [[ 0.  1.  2.  3.]
#  [ 4.  5.  6.  7.]
#  [ 8.  9. 10. 11.]]
# #
# print(arr[0])
##
# [0. 1. 2. 3.]
# #

# print(arr-arr[0])
##
# [[0. 0. 0. 0.]
#  [4. 4. 4. 4.]
#  [8. 8. 8. 8.]]
# #

# now with DataFrame
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

# print(frame)
##
#         b   d   e
# Utah    0   1   2
# Ohio    3   4   5
# Texas   6   7   8
# Oregon  9  10  11
# #

series = frame.iloc[0]
# print(series)
##
# b    0
# d    1
# e    2
# Name: Utah, dtype: int32
# #

broadcast_operations = frame - series
# print(broadcast_operations)
##
#         b  d  e
# Utah    0  0  0
# Ohio    3  3  3
# Texas   6  6  6
# Oregon  9  9  9
# #

series2 = pd.Series(np.arange(3), index=list('bef'))
# print(series2)
##
# b    0
# e    1
# f    2
# dtype: int32

# print(frame)
##
#         b   d   e
# Utah    0   1   2
# Ohio    3   4   5
# Texas   6   7   8
# Oregon  9  10  11
# #

# print(frame+series2)
##
#           b   d     e   f
# Utah    0.0 NaN   3.0 NaN
# Ohio    3.0 NaN   6.0 NaN
# Texas   6.0 NaN   9.0 NaN
# Oregon  9.0 NaN  12.0 NaN
# #

series3 = frame['d']
# print(series3)
##
# Utah       1
# Ohio       4
# Texas      7
# Oregon    10
# Name: d, dtype: int32
# #

# print(frame.sub(series3, axis='index'))
##
#         b  d  e
# Utah   -1  0  1
# Ohio   -1  0  1
# Texas  -1  0  1
# Oregon -1  0  1
# #

# Function Application and Maping
# NumPy ufuncs (element-wise array methods) also work with pandas objects:

frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])


# print(frame)
# /
#                b         d         e
# Utah   -1.330074  0.040842  1.790817
# Ohio   -0.235221 -0.066568 -2.182658
# Texas  -0.448620 -1.330768 -1.056096
# Oregon -0.545503  0.385723 -0.514618
# /#

# print(np.abs(frame))
# /
#                b         d         e
# Utah    1.145553  1.797416  0.110079
# Ohio    0.847067  0.358707  1.658399
# Texas   0.773686  1.681025  0.013541
# Oregon  1.292587  0.180627  1.673120
# /#

def f1(x):
    return x.max() - x.min()


result = frame.apply(f1)


# print(frame)
# /
#                b         d         e
# Utah   -0.324420  0.113594 -0.092740
# Ohio    0.964953 -0.494764  0.521877
# Texas  -1.669681  0.028036  1.173617
# Oregon -0.384464  0.520960  1.284386
# /#
# print(result)
# /
# b    1.514911
# d    1.130885
# e    2.709770
# dtype: float64
# /#

# print(frame.apply(f1,axis='columns'))
# /
# Utah      1.344964
# Ohio      0.580744
# Texas     1.831892
# Oregon    1.155960
# dtype: float64
# /#

# def f2(x):
#     return pd.Series([x.min(),x.max()],index=['min','max'])
#
# print(frame.apply(f2))

def my_format(x):
    return f"{x:.2f}"


# print(frame.applymap(my_format))
# /
#             b      d      e
# Utah     0.63   1.46  -1.34
# Ohio    -0.59  -1.22   0.29
# Texas   -1.29  -0.29   0.51
# Oregon   0.54  -1.75   0.34
# /#


# print(frame['e'].map(my_format))
# /
# Utah      -0.18
# Ohio       0.86
# Texas     -1.01
# Oregon     0.58
# Name: e, dtype: object
# /#

# Sorting and Ranking

obj = pd.Series(np.arange(4), index=['d', 'b', 'a', 'c'])
# print(obj)
# /
# d    0
# b    1
# a    2
# c    3
# dtype: int32
# /#

sort_obj = obj.sort_index()
# print(sort_obj)
# /
# a    2
# b    1
# c    3
# d    0
# dtype: int32
# /#

frame = pd.DataFrame(np.arange(8).reshape((4,2)),
                     columns=['three', 'one'],
                     index=['d', 'a', 'b', 'c'])

# print(frame)
#/
#    three  one
# d      0    1
# a      2    3
# b      4    5
# c      6    7
# /#

# sorting by indexing

# print(frame.sort_index(axis='index'))
##
#    three  one
# a      2    3
# b      4    5
# c      6    7
# d      0    1
# #

# sorting by columns

# print(frame.sort_index(axis='columns'))
##
#    one  three
# d    1      0
# a    3      2
# b    5      4
# c    7      6
# #

# sorting the columns by asecending and descending order

# print(frame.sort_index(ascending=False))
##
#    three  one
# d      0    1
# c      6    7
# b      4    5
# a      2    3
# #

# print(frame.sort_index(axis='columns',ascending=False))
##
#    three  one
# d      0    1
# a      2    3
# b      4    5
# c      6    7
# #

# sorting by values we need to use sort_values()

obj=pd.Series([3,2,6,9],index=[3,2,4,5])
# print(obj.sort_values())
##
# 2    2
# 3    3
# 4    6
# 5    9
# dtype: int64
# #

# print(obj.sort_values(ascending=False))
##
# 5    9
# 4    6
# 3    3
# 2    2
# dtype: int64
# #

# sorting the Nan values
# Nan is always sorted last by default
obj2=pd.Series([5,2,np.nan,8,np.nan,1,np.nan])
# print(obj2.sort_values())
##
# 5    1.0
# 1    2.0
# 0    5.0
# 3    8.0
# 2    NaN
# 4    NaN
# 6    NaN
# dtype: float64
# #

# we can sort Nan is first position
# print(obj2.sort_values(na_position='first'))
##
# 2    NaN
# 4    NaN
# 6    NaN
# 5    1.0
# 1    2.0
# 0    5.0
# 3    8.0
# dtype: float64
# #

# When sorting a DataFrame, you can use the data in one or more columns as the sort keys.
# To do so, pass one or more column names to sort_values:

frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
# print(frame)
##
#    b  a
# 0  4  0
# 1  7  1
# 2 -3  0
# 3  2  1
# #

# print(frame.sort_values('b'))
##
#    b  a
# 2 -3  0
# 3  2  1
# 0  4  0
# 1  7  1
# #

# to sort multiple columns by passing list is fine]
# print(frame.sort_values(['a','b']))
##
#    b  a
# 2 -3  0
# 0  4  0
# 3  2  1
# 1  7  1
# #


# Ranking assigns ranks from one through the number of valid data points in an array,
# starting from the lowest value. The rank methods for Series and DataFrame are the place to look;
# by default, rank breaks ties by assigning each group the mean rank:

obj=pd.Series([7, -5, 7, 4, 2, 0, 4])
# print(obj.rank())
##
# 0    6.5
# 1    1.0
# 2    6.5
# 3    4.5
# 4    3.0
# 5    2.0
# 6    4.5
# dtype: float64
# #

# print(obj.rank(method='first'))
##
# 0    6.0
# 1    1.0
# 2    7.0
# 3    4.0
# 4    3.0
# 5    2.0
# 6    5.0
# dtype: float64
# #

# you can ranking descending order
# print(obj.rank(ascending=False))
##
# 0    1.5
# 1    7.0
# 2    1.5
# 3    3.5
# 4    5.0
# 5    6.0
# 6    3.5
# dtype: float64
# #

# DataFrame can compute ranks over the rows or the columns:

frame=pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],"c": [-2, 5, 8, -2.5]})
# print(frame)
##
#      b  a    c
# 0  4.3  0 -2.0
# 1  7.0  1  5.0
# 2 -3.0  0  8.0
# 3  2.0  1 -2.5
# #

# print(frame.rank(axis='columns'))
##
#      b    a    c
# 0  3.0  2.0  1.0
# 1  3.0  1.0  2.0
# 2  1.0  2.0  3.0
# 3  3.0  2.0  1.0
# #

# Axis Indexes with duplicate Labels
# lets consider the small series of duplicate values

obj = pd.Series(np.arange(5),index=['b','b','a','a','c'])
# print(obj)
##
# b    0
# b    1
# a    2
# a    3
# c    4
# dtype: int32
# #

# The is_unique property of the index can tell you whether or not its labels are unique:

# print(obj.index.is_unique)
##
# False
# #

# print(obj['a'])
##
# a    2
# a    3
# dtype: int32
# #

# print(obj['c'])
# 4

# This can make your code more complicated, as the output type from indexing can vary based on
# whether or not a label is repeated.
#
# The same logic extends to indexing rows (or columns) in a DataFrame:

frame=pd.DataFrame(np.random.standard_normal((5,3)),
                   index=list('aabbc'))
# print(frame)
##
#           0         1         2
# a  0.330885  0.902583  1.786726
# a -0.506146 -0.245844  1.181333
# b -0.318012 -0.855817 -0.456280
# b  0.384331  0.574272  0.457466
# c  0.199499 -0.968973  0.341253
# #

# locating the labels 'b'
# print(frame.loc['b'])
##
#           0         1         2
# b  0.446420  0.745531  0.033860
# b -0.546735  0.515392  0.196446
# #

# print(frame.loc['c'])
##
# 0    0.194780
# 1   -0.891296
# 2   -0.818945
# Name: c, dtype: float64
# #

# 5.3 Summarizing and Computing Descriptive Statistics

# df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
#                   index=list('abcd'),
#                   columns=['one','two'])
# print(df)
##
#     one  two
# a  1.40  NaN
# b  7.10 -4.5
# c   NaN  NaN
# d  0.75 -1.3
# #

# Calling DataFrame's Sum method it returns series of columns values

# print(df.sum())
##
# one    9.25
# two   -5.80
# dtype: float64
# #

# Passing axis='columns' or axis=1 sum across the columns instead
# print(df.sum(axis='columns'))
##
# a    1.40
# b    2.60
# c    0.00
# d   -0.55
# dtype: float64
# #

# print(df.sum(axis='index',skipna=False))
##
# one   NaN
# two   NaN
# dtype: float64
# #

# print(df.sum(axis='columns',skipna=False))
##
# a     NaN
# b    2.60
# c     NaN
# d   -0.55
# dtype: float64
# #

# print(df.sum(axis='index',skipna=True))
##
# one    9.25
# two   -5.80
# dtype: float64
# #

# print(df.sum(axis='columns',skipna=True))
##
# a    1.40
# b    2.60
# c    0.00
# d   -0.55
# dtype: float64
# #

# Some aggregations, like mean, require at least one non-NA value to yield a value result, so here we have:

# print(df.mean(axis='columns'))
##
# a    1.400
# b    1.300
# c      NaN
# d   -0.275
# dtype: float64
# #

# print(df.describe())
##
#             one       two
# count  3.000000  2.000000
# mean   3.083333 -2.900000
# std    3.493685  2.262742
# min    0.750000 -4.500000
# 25%    1.075000 -3.700000
# 50%    1.400000 -2.900000
# 75%    4.250000 -2.100000
# max    7.100000 -1.300000
# #

# non numberic data

# obj=pd.Series(list('abcde'*4))
# print(obj.describe())
##
# count     20
# unique     5
# top        a
# freq       4
# dtype: object
# #
