In [56]:
# import numpy library
import numpy as np

Numpy - Numerical python

Numpy useage:
- ndarray, a multi dimensional array providing fast array oriented arithmetic operations and flexibility broadcasting capabilities.
- mathematical functions for fast opeartions on entire arrays data without having to write for loops.
- tools for reading/writing array data to disk and working with memory files .
- linear algebra, random number generation and fourier transform capabilities.

for most data analysis applications, the main areas of functionality i'll focus on are:
- fast array based opeartions for munging and cleaning, subsetting and filtering, transformation other kind of computations.
- common array algorithm like sorting, unique and set opeartions.
- effcient descriptive statistics and aggeregate/summerizing data.
- data alignment and relational data manipulations for merging and heterogeneous datasets.
- expressing conditional loggic has array expressions instead of loops with if-elif-else branches.
- group wise data manipulations( aggregation, transformation and function application ).

why numpy?

one of the reason is numpy is so important for numerical computation in python it is designed for large arrays of data.

- numpy array stores data in contiguous block of memory, independent in other built in python objects.
- numpy arrays also use very less memory than in other build in python sequences.
- numpy arrays performs complex computation opeations without using pythons for loop, in python it can be slow process for large
    datasets.
- numpy is faster than python code. because numpy written in C based algorithms.

In [57]:
# lets showing diffrence numpy array vs python array
my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

print('Numpy array')
%timeit my_arr2 = my_arr * 2
print()
print()

print('Python array')
%timeit my_list2 = [x * 2 for x in my_list]
print()

# numpy array genrally 10 to 100 times faster than the pure python counterparts and use significantly less memory

Numpy array
5.37 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Python array
203 ms ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



1.1 A NumPy ndarray: A Multidimensional Object.
-

In [58]:
# create a simple numpy array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [59]:
# multiply by 2
arr * 2 

array([2, 4, 6])

In [60]:
# addition 
arr + arr

array([2, 4, 6])

In [61]:
arr = np.array([[1,2,3],[4,5,6]])
print('Shape => ',arr.shape)
print('Dtype => ',arr.dtype)

Shape =>  (2, 3)
Dtype =>  int32


In [62]:
# creating ndarray by using array function
data1 = np.array([3,2,6,9,3])
data1

array([3, 2, 6, 9, 3])

In [63]:
# multi-dimensional array
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
# check the arr2 dimensions
arr2.ndim

2

In [65]:
# chech arr2 shape
arr2.shape

(2, 3)

In [66]:
# lets check the data type 
arr2.dtype

dtype('int32')

In [67]:
# there is other ways to create arrays other than numpy array like we have zeros, ones and empty functions.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [68]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
np.empty(10) # don't assume empty always returns 1s its used garbage values.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
np.zeros((3,4)) # by default numpy will assume float64

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [72]:
# numpy we have arange function like in python we have range function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(10).dtype

dtype('int32')

In [74]:
# datatypes for ndarrays
arr1 = np.array([1,2,3],dtype='int64')
arr2 = np.array([1,2,3],dtype='float64')

arr1.dtype

dtype('int64')

In [75]:
arr2.dtype

dtype('float64')

In [76]:
# explicitly we can convert or cast the one data type into another data type
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr.dtype)

float_arr = arr1.astype('float64')
print(float_arr)
print(float_arr.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float64


In [77]:
# when we convert float into integers the decimal points are truncated.
arr1 = np.array([1.1,2.2,3.3,4.4])
print(arr1)
int_arr = arr1.astype('int64')
print(int_arr) # as you can see that decimal values are removed or ignored.
print(int_arr.dtype)

[1.1 2.2 3.3 4.4]
[1 2 3 4]
int64


In [78]:
# lets convert strings of numbers into integers or floats
str_arr = np.array(["1.1",'2.2','3.3','4.4'])
print(str_arr)
print()
float_arr = str_arr.astype('float64')
print(float_arr)
print(float_arr.dtype)

['1.1' '2.2' '3.3' '4.4']

[1.1 2.2 3.3 4.4]
float64


In [79]:
# one more casting example
int_arr = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype=np.float64)
int_arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [80]:
# Arithmetic with numpy arrays

arr = np.array([[1,2,3],[4,5,6]],dtype='float64')
print('Addition')
print(arr + arr)
print()
print('Subtract')
print(arr - 2)
print()
print('Divide')
print(arr / 2)

Addition
[[ 2.  4.  6.]
 [ 8. 10. 12.]]

Subtract
[[-1.  0.  1.]
 [ 2.  3.  4.]]

Divide
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [81]:
# square the each value
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [82]:
# compare the two arrays
arr2 = np.array([[5,6,2],[2,3,9]])
arr2 > arr

array([[ True,  True, False],
       [False, False,  True]])

In [83]:
# basic indexing and slicing
arr = np.arange(10)
arr
print(arr[5])
print(arr[5:8])
arr[5:8]=12
arr

5
[5 6 7]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Note : one important thing, in python built in lists array slices are views in orginal array. this means its not create copy of data
whatever we changed in array slices it will reflect the orginal source array

In [84]:
# anychanges in array slices it will reflect the orginal array, look below example for better understand
print(arr)
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1]=12345
print(arr_slice)
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [86]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [91]:
# here we created for copy f orginal data. any changes in copy array data will not reflect the orginal array data
slice_arr = [1,2,3,4,5]
copy_arr = slice_arr.copy()
copy_arr[2] = 7
print(slice_arr)
print(copy_arr)

[1, 2, 3, 4, 5]
[1, 2, 7, 4, 5]


In [97]:
# lets look into 2-Dimensional array
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [98]:
# access the element values
arr2d[0][2]

3

In [99]:
arr2d[0,2] # above code and this code both give same results.

3

In [112]:
# 3_dimensional data
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [113]:
arr3d[0] # 2-D data

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [116]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [117]:
arr3d[1,0]

array([7, 8, 9])

In [120]:
# above code expanded into two lines
temp_1 = arr3d[1]
temp_1
temp_1[0]

array([7, 8, 9])

In [122]:
# indexing with slicing
arr = np.arange(10)
arr[1:6]

array([1, 2, 3, 4, 5])

In [123]:
# 2d
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [130]:
arr2d[1,:2]

array([4, 5])

In [133]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [135]:
# boolean indexing
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [136]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [137]:
data[names=='Bob']

array([[4, 7],
       [0, 0]])

In [138]:
data[names=='Bob',1:]

array([[7],
       [0]])

In [139]:
data[names == 'Bob',1]

array([7, 0])

In [144]:
data[names != 'Bob',0]

array([  0,  -5,   1, -12,   3])

In [149]:
data[~(names == 'Bob')]
# the ~ opeartor is useful when you want invert the boolean array referenced by variable

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [152]:
data[(names=='Bob') | (names=='Will')]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [ ]:
# selecting data from array an boolean indexing and assigning the results into new varible always creates a copy of the data
# python keywords and or not work in boolean arrays. so use &(and) |(or)

In [153]:
data[data<0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [159]:
# we can whole set rows or columns using one dimensional boolean array data
data[names!='Joe']=7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])