# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Cloud Lab/Colab Notebooks/Part 8 - Deep Learning/1. Aritificial Neural Networks ( ANN )/Copy of Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
dataset = []
for i in X[:5]:
  dataset.append(i)
dataset

[array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       dtype=object),
 array([608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       dtype=object),
 array([502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       dtype=object),
 array([699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       dtype=object),
 array([850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       dtype=object)]

  ### Importing the dataset

### Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

Label Encoding the "Gender" column

In [ ]:
lb = LabelEncoder()
X[:,2] = lb.fit_transform(X[:,2])

In [ ]:
dataset = []
for i in X[:5]:
  dataset.append(i)
dataset

[array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object),
 array([608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58], dtype=object),
 array([502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       dtype=object),
 array([699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63], dtype=object),
 array([850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1], dtype=object)]

One Hot Encoding the "Geography" column

In [ ]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
dataset = []
for i in X[:5]:
  dataset.append(i)
dataset

[array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       dtype=object),
 array([0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       dtype=object),
 array([1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       dtype=object),
 array([1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63], dtype=object),
 array([0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       dtype=object)]

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

### Feature Scaling

feature scaling is very important for deep learning


In [ ]:
dataset = []
for i in X_train[:5]:
  dataset.append(i)
dataset

[array([0.0, 0.0, 1.0, 667, 0, 34, 5, 0.0, 2, 1, 0, 163830.64],
       dtype=object),
 array([0.0, 1.0, 0.0, 427, 1, 42, 1, 75681.52, 1, 1, 1, 57098.0],
       dtype=object),
 array([1.0, 0.0, 0.0, 535, 0, 29, 2, 112367.34, 1, 1, 0, 185630.76],
       dtype=object),
 array([0.0, 0.0, 1.0, 654, 1, 40, 5, 105683.63, 1, 1, 0, 173617.09],
       dtype=object),
 array([0.0, 0.0, 1.0, 850, 0, 57, 8, 126776.3, 2, 1, 1, 132298.49],
       dtype=object)]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [ ]:
dataset = []
for i in X_train[:5]:
  dataset.append(i)
dataset

[array([-1.01460667, -0.5698444 ,  1.74309049,  0.16958176, -1.09168714,
        -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,  0.64259497,
        -1.03227043,  1.10643166]),
 array([-1.01460667,  1.75486502, -0.57369368, -2.30455945,  0.91601335,
         0.30102557, -1.37744033, -0.00631193, -0.92159124,  0.64259497,
         0.9687384 , -0.74866447]),
 array([ 0.98560362, -0.5698444 , -0.57369368, -1.19119591, -1.09168714,
        -0.94312892, -1.031415  ,  0.57993469, -0.92159124,  0.64259497,
        -1.03227043,  1.48533467]),
 array([-1.01460667, -0.5698444 ,  1.74309049,  0.03556578,  0.91601335,
         0.10961719,  0.00666099,  0.47312769, -0.92159124,  0.64259497,
        -1.03227043,  1.27652776]),
 array([-1.01460667, -0.5698444 ,  1.74309049,  2.05611444, -1.09168714,
         1.73658844,  1.04473698,  0.8101927 ,  0.8095029 ,  0.64259497,
         0.9687384 ,  0.55837842])]

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the inpsut layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))


### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

adam
- adam stands for Adaptive Moment Estimation (adam)
- adam optimizer often used in training deep learning neural networks
- it combines ideas from two other popular optimizers
  - RMS prop
  - Momentum
- adaptiveness-> adamp adapts the learning rate of each parameter.it maintaines the separate learning rate for each parameters and updates them based on their post gradients
- Momentum-> its used concept of momentum to spped up convergence. momentum helps the optimizer to continue same direction, even when gradients are small, allowing for faster convergence
- RMSprop-> adam used this RMSprop algorithm to adjusts the learning rates of each parameter based on magnitude of recent gradients


---

loss  = 'binary_crossentropy' or loss = 'categorical_crossentropy'

- in binary classification problems we have to use ***binary_crossentropy***
- multi-class classification problems we have to use ***categorical_crossentropy***




In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5983 - accuracy: 0.7440
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4986 - accuracy: 0.7966
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4557 - accuracy: 0.8023
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4320 - accuracy: 0.8144
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4208 - accuracy: 0.8211
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4135 - accuracy: 0.8260
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4080 - accuracy: 0.8291
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8304
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8311
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3971 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 113ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

63/63 [==============================] - 0s 2ms/step


array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_pred, y_test)
print(cm)
accuracy = accuracy_score(y_pred, y_test)
print(accuracy)

[[1493  180]
 [ 102  225]]
0.859
